# Generated by Django 5.1.4 on 2024-12-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Lipsticks'), (2, 'Foundations'), (3, 'Compacts'), (4, 'Eyeshadows'), (5, 'Nails'), (6, 'Cheeks'), (7, 'Lotions')], verbose_name='Categories'),
        ),
    ]
