# Generated by Django 5.1.4 on 2024-12-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore_app', '0003_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Lipsticks'), (2, 'Foundations'), (3, 'Compacts'), (4, 'Eye-Makeup'), (5, 'Nails'), (6, 'Makeup'), (7, 'Lotions')], verbose_name='Categories'),
        ),
    ]
