# Generated by Django 5.1.4 on 2024-12-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore_app', '0006_alter_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
    ]
