# Generated by Django 5.1.4 on 2024-12-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore_app', '0007_order_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
    ]
